createEvent:
  name: ${self:custom.base}-create-event
  handler: services/events/src/create-event.main
  events:
    - httpApi: 'POST /events'
  environment:
    BUCKET: picpuc
  package:
    include:
      - services/events/src/create-event.js
      - lib/errors/database-error.js
      - lib/image.js
      - lib/responses.js

getEventsDate:
  name: ${self:custom.base}-get-events-date
  handler: services/events/src/get-events-date.main
  events:
    - httpApi: 'GET /events/date/{coords}/{order}'
  package:
    include:
      - services/events/src/get-events-date.js
      - lib/errors/database-error.js

getEventsNear:
  name: ${self:custom.base}-get-events-near
  handler: services/events/src/get-events-near.handle
  events:
    - httpApi: 'GET /events/near/{coords}'
  package:
    include:
      - services/events/src/get-events-near.js
      - lib/errors/database-error.js
